// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: message.proto
// </auto-generated>

using System.Collections.Generic;
using Newtonsoft.Json;

namespace DanmakuBackend.Models.ProtoEntity
{
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
    [global::ProtoBuf.ProtoContract()]
    public partial class Response : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"messages")]
        public global::System.Collections.Generic.List<Message> Messages { get; } = new global::System.Collections.Generic.List<Message>();

        [global::ProtoBuf.ProtoMember(2, Name = @"cursor")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Cursor { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"fetchInterval")]
        public long fetchInterval { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"now")]
        public long Now { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"internalExt")]
        [global::System.ComponentModel.DefaultValue("")]
        public string internalExt { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6, Name = @"fetchType")]
        public int fetchType { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<string, string> routeParams { get; } = new global::System.Collections.Generic.Dictionary<string, string>();

        [global::ProtoBuf.ProtoMember(8, Name = @"heartbeatDuration")]
        public long heartbeatDuration { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"needAck")]
        public bool needAck { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"pushServer")]
        [global::System.ComponentModel.DefaultValue("")]
        public string pushServer { get; set; } = "";

        [global::ProtoBuf.ProtoMember(11, Name = @"liveCursor")]
        [global::System.ComponentModel.DefaultValue("")]
        public string liveCursor { get; set; } = "";

        [global::ProtoBuf.ProtoMember(12, Name = @"historyNoMore")]
        public bool historyNoMore { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Message : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"method")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Method { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"payload")]
        public byte[] Payload { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"msgId")]
        public long msgId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"msgType")]
        public int msgType { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"offset")]
        public long Offset { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Common : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"method")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Method { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"msgId")]
        public long msgId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"roomId")]
        public long roomId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"createTime")]
        public long createTime { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"monitor")]
        public int Monitor { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"isShowMsg")]
        public bool isShowMsg { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"describe")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Describe { get; set; } = "";

        [global::ProtoBuf.ProtoMember(8, Name = @"displayText")]
        public Text displayText { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"foldType")]
        public long foldType { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"anchorFoldType")]
        public long anchorFoldType { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"priorityScore")]
        public long priorityScore { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"logId")]
        [global::System.ComponentModel.DefaultValue("")]
        public string logId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(13, Name = @"msgProcessFilterK")]
        [global::System.ComponentModel.DefaultValue("")]
        public string msgProcessFilterK { get; set; } = "";

        [global::ProtoBuf.ProtoMember(14, Name = @"msgProcessFilterV")]
        [global::System.ComponentModel.DefaultValue("")]
        public string msgProcessFilterV { get; set; } = "";

        [global::ProtoBuf.ProtoMember(15, Name = @"user")]
        public User User { get; set; }

        [global::ProtoBuf.ProtoMember(16, Name = @"room")]
        public Room Room { get; set; }

        [global::ProtoBuf.ProtoMember(17, Name = @"anchorFoldTypeV2")]
        public long anchorFoldTypeV2 { get; set; }

        [global::ProtoBuf.ProtoMember(18, Name = @"processAtSeiTimeMs")]
        public long processAtSeiTimeMs { get; set; }

        [global::ProtoBuf.ProtoMember(24, Name = @"appId")]
        public long appId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Text : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"key")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Key { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"defaultPattern")]
        [global::System.ComponentModel.DefaultValue("")]
        public string defaultPattern { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"defaultFormat")]
        public TextFormat defaultFormat { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"pieces")]
        public global::System.Collections.Generic.List<TextPiece> Pieces { get; } = new global::System.Collections.Generic.List<TextPiece>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Room : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public long Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"idStr")]
        [global::System.ComponentModel.DefaultValue("")]
        public string idStr { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"status")]
        public long Status { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"ownerUserId")]
        public long ownerUserId { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"title")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Title { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6, Name = @"userCount")]
        public long userCount { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"createTime")]
        public long createTime { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"linkmicLayout")]
        public long linkmicLayout { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"finishTime")]
        public long finishTime { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"extra")]
        public RoomExtra Extra { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"dynamicCoverUri")]
        [global::System.ComponentModel.DefaultValue("")]
        public string dynamicCoverUri { get; set; } = "";

        [global::ProtoBuf.ProtoMember(12)]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<long, string> dynamicCoverDict { get; } = new global::System.Collections.Generic.Dictionary<long, string>();

        [global::ProtoBuf.ProtoMember(13, Name = @"lastPingTime")]
        public long lastPingTime { get; set; }

        [global::ProtoBuf.ProtoMember(14, Name = @"liveId")]
        public long liveId { get; set; }

        [global::ProtoBuf.ProtoMember(15, Name = @"streamProvider")]
        public long streamProvider { get; set; }

        [global::ProtoBuf.ProtoMember(16, Name = @"osType")]
        public long osType { get; set; }

        [global::ProtoBuf.ProtoMember(17, Name = @"clientVersion")]
        public long clientVersion { get; set; }

        [global::ProtoBuf.ProtoMember(18, Name = @"withLinkmic")]
        public bool withLinkmic { get; set; }

        [global::ProtoBuf.ProtoMember(19, Name = @"enableRoomPerspective")]
        public bool enableRoomPerspective { get; set; }

        [global::ProtoBuf.ProtoMember(20, Name = @"cover")]
        public Image Cover { get; set; }

        [global::ProtoBuf.ProtoMember(21, Name = @"dynamicCover")]
        public Image dynamicCover { get; set; }

        [global::ProtoBuf.ProtoMember(22, Name = @"dynamicCoverLow")]
        public Image dynamicCoverLow { get; set; }

        [global::ProtoBuf.ProtoMember(23, Name = @"shareUrl")]
        [global::System.ComponentModel.DefaultValue("")]
        public string shareUrl { get; set; } = "";

        [global::ProtoBuf.ProtoMember(24, Name = @"anchorShareText")]
        [global::System.ComponentModel.DefaultValue("")]
        public string anchorShareText { get; set; } = "";

        [global::ProtoBuf.ProtoMember(25, Name = @"userShareText")]
        [global::System.ComponentModel.DefaultValue("")]
        public string userShareText { get; set; } = "";

        [global::ProtoBuf.ProtoMember(26, Name = @"streamId")]
        public long streamId { get; set; }

        [global::ProtoBuf.ProtoMember(27, Name = @"streamIdStr")]
        [global::System.ComponentModel.DefaultValue("")]
        public string streamIdStr { get; set; } = "";

        [global::ProtoBuf.ProtoMember(28, Name = @"streamUrl")]
        public StreamUrl streamUrl { get; set; }

        [global::ProtoBuf.ProtoMember(29, Name = @"mosaicStatus")]
        public long mosaicStatus { get; set; }

        [global::ProtoBuf.ProtoMember(30, Name = @"mosaicTip")]
        [global::System.ComponentModel.DefaultValue("")]
        public string mosaicTip { get; set; } = "";

        [global::ProtoBuf.ProtoMember(31, Name = @"cellStyle")]
        public long cellStyle { get; set; }

        [global::ProtoBuf.ProtoMember(32, Name = @"linkMic")]
        public LinkMic linkMic { get; set; }

        [global::ProtoBuf.ProtoMember(33, Name = @"luckymoneyNum")]
        public long luckymoneyNum { get; set; }

        [global::ProtoBuf.ProtoMember(34, Name = @"decoList")]
        public global::System.Collections.Generic.List<Decoration> decoList { get; } = new global::System.Collections.Generic.List<Decoration>();

        [global::ProtoBuf.ProtoMember(35, Name = @"topFans")]
        public global::System.Collections.Generic.List<TopFan> topFans { get; } = new global::System.Collections.Generic.List<TopFan>();

        [global::ProtoBuf.ProtoMember(36, Name = @"stats")]
        public RoomStats Stats { get; set; }

        [global::ProtoBuf.ProtoMember(37, Name = @"sunDailyIconContent")]
        [global::System.ComponentModel.DefaultValue("")]
        public string sunDailyIconContent { get; set; } = "";

        [global::ProtoBuf.ProtoMember(38, Name = @"distance")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Distance { get; set; } = "";

        [global::ProtoBuf.ProtoMember(39, Name = @"distanceCity")]
        [global::System.ComponentModel.DefaultValue("")]
        public string distanceCity { get; set; } = "";

        [global::ProtoBuf.ProtoMember(40, Name = @"location")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Location { get; set; } = "";

        [global::ProtoBuf.ProtoMember(41, Name = @"realDistance")]
        [global::System.ComponentModel.DefaultValue("")]
        public string realDistance { get; set; } = "";

        [global::ProtoBuf.ProtoMember(42, Name = @"feedRoomLabel")]
        public Image feedRoomLabel { get; set; }

        [global::ProtoBuf.ProtoMember(43, Name = @"commonLabelList")]
        [global::System.ComponentModel.DefaultValue("")]
        public string commonLabelList { get; set; } = "";

        [global::ProtoBuf.ProtoMember(44, Name = @"livingRoomAttrs")]
        public RoomUserAttr livingRoomAttrs { get; set; }

        [global::ProtoBuf.ProtoMember(45, Name = @"adminUserIds")]
        public global::System.Collections.Generic.List<long> adminUserIds { get; } = new global::System.Collections.Generic.List<long>();

        [global::ProtoBuf.ProtoMember(46, Name = @"owner")]
        public User Owner { get; set; }

        [global::ProtoBuf.ProtoMember(47, Name = @"privateInfo")]
        [global::System.ComponentModel.DefaultValue("")]
        public string privateInfo { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RoomExtra : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RoomStats : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RoomUserAttr : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StreamUrl : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LinkMic : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Decoration : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TopFan : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class User : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public long Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"shortId")]
        public long shortId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"nickname")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Nickname { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"gender")]
        public int Gender { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"signature")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Signature { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6, Name = @"level")]
        public int Level { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"birthday")]
        public long Birthday { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"telephone")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Telephone { get; set; } = "";

        [global::ProtoBuf.ProtoMember(9, Name = @"avatarThumb")]
        public Image avatarThumb { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"avatarMedium")]
        public Image avatarMedium { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"avatarLarge")]
        public Image avatarLarge { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"verified")]
        public bool Verified { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"experience")]
        public int Experience { get; set; }

        [global::ProtoBuf.ProtoMember(14, Name = @"city")]
        [global::System.ComponentModel.DefaultValue("")]
        public string City { get; set; } = "";

        [global::ProtoBuf.ProtoMember(15, Name = @"status")]
        public int Status { get; set; }

        [global::ProtoBuf.ProtoMember(16, Name = @"createTime")]
        public long createTime { get; set; }

        [global::ProtoBuf.ProtoMember(17, Name = @"modifyTime")]
        public long modifyTime { get; set; }

        [global::ProtoBuf.ProtoMember(18, Name = @"secret")]
        public int Secret { get; set; }

        [global::ProtoBuf.ProtoMember(19, Name = @"shareQrcodeUri")]
        [global::System.ComponentModel.DefaultValue("")]
        public string shareQrcodeUri { get; set; } = "";

        [global::ProtoBuf.ProtoMember(20, Name = @"incomeSharePercent")]
        public int incomeSharePercent { get; set; }

        [global::ProtoBuf.ProtoMember(21, Name = @"badgeImageList")]
        public Image badgeImageList { get; set; }

        [global::ProtoBuf.ProtoMember(22, Name = @"followInfo")]
        public FollowInfo followInfo { get; set; }

        [global::ProtoBuf.ProtoMember(23, Name = @"payGrade")]
        public PayGrade payGrade { get; set; }

        [global::ProtoBuf.ProtoMember(24, Name = @"fansClub")]
        public FansClub fansClub { get; set; }

        [global::ProtoBuf.ProtoMember(26, Name = @"specialId")]
        [global::System.ComponentModel.DefaultValue("")]
        public string specialId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(27, Name = @"avatarBorder")]
        public Image avatarBorder { get; set; }

        [global::ProtoBuf.ProtoMember(28, Name = @"medal")]
        public Image Medal { get; set; }

        [global::ProtoBuf.ProtoMember(29, Name = @"realTimeIcons")]
        public global::System.Collections.Generic.List<Image> realTimeIcons { get; } = new global::System.Collections.Generic.List<Image>();

        [global::ProtoBuf.ProtoMember(30, Name = @"newRealTimeIcons")]
        public global::System.Collections.Generic.List<Image> newRealTimeIcons { get; } = new global::System.Collections.Generic.List<Image>();

        [global::ProtoBuf.ProtoMember(31, Name = @"topVipNo")]
        public long topVipNo { get; set; }

        [global::ProtoBuf.ProtoMember(32, Name = @"userAttr")]
        public UserAttr userAttr { get; set; }

        [global::ProtoBuf.ProtoMember(33, Name = @"ownRoom")]
        public OwnRoom ownRoom { get; set; }

        [global::ProtoBuf.ProtoMember(34, Name = @"payScore")]
        public long payScore { get; set; }

        [global::ProtoBuf.ProtoMember(35, Name = @"ticketCount")]
        public long ticketCount { get; set; }

        [global::ProtoBuf.ProtoMember(36, Name = @"anchorInfo")]
        public AnchorInfo anchorInfo { get; set; }

        [global::ProtoBuf.ProtoMember(37, Name = @"linkMicStats")]
        public int linkMicStats { get; set; }

        [global::ProtoBuf.ProtoMember(38, Name = @"displayId")]
        [global::System.ComponentModel.DefaultValue("")]
        public string displayId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(59, Name = @"userVipInfo")]
        public UserVIPInfo userVipInfo { get; set; }

        [global::ProtoBuf.ProtoMember(61, Name = @"badgeImageListV2")]
        public global::System.Collections.Generic.List<Image> badgeImageListV2 { get; } = new global::System.Collections.Generic.List<Image>();

        [global::ProtoBuf.ProtoMember(67, Name = @"webRid")]
        [global::System.ComponentModel.DefaultValue("")]
        public string webRid { get; set; } = "";

        [global::ProtoBuf.ProtoMember(70, Name = @"subscribe")]
        public Subscribe Subscribe { get; set; }

        [global::ProtoBuf.ProtoMember(73, Name = @"webcastUid")]
        [global::System.ComponentModel.DefaultValue("")]
        public string webcastUid { get; set; } = "";

        [global::ProtoBuf.ProtoMember(46, Name = @"sec_uid")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Sec_uid { get; set; } = "";

        [global::ProtoBuf.ProtoMember(47, Name = @"user_role")]
        public int User_role { get; set; }

        [global::ProtoBuf.ProtoMember(1029, Name = @"is_follower")]
        public bool Is_follower { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class UserAttr : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"isMuted")]
            public bool isMuted { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"isAdmin")]
            public bool isAdmin { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"isSuperAdmin")]
            public bool isSuperAdmin { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"adminPrivileges")]
            public global::System.Collections.Generic.List<int> adminPrivileges { get; } = new global::System.Collections.Generic.List<int>();

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class OwnRoom : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"roomIds")]
            public global::System.Collections.Generic.List<long> roomIds { get; } = new global::System.Collections.Generic.List<long>();

            [global::ProtoBuf.ProtoMember(2, Name = @"roomIdsStr")]
            public global::System.Collections.Generic.List<string> roomIdsStr { get; } = new global::System.Collections.Generic.List<string>();

            [global::ProtoBuf.ProtoMember(3, Name = @"roomIdsDisplay")]
            public global::System.Collections.Generic.List<int> roomIdsDisplay { get; } = new global::System.Collections.Generic.List<int>();

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class AnchorInfo : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class GradeBuffInfo : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"buffLevel")]
            public long buffLevel { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"status")]
            public int Status { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"endTime")]
            public long endTime { get; set; }

            [global::ProtoBuf.ProtoMember(4)]
            [global::ProtoBuf.ProtoMap]
            public global::System.Collections.Generic.Dictionary<long, long> statsInfo { get; } = new global::System.Collections.Generic.Dictionary<long, long>();

            [global::ProtoBuf.ProtoMember(5, Name = @"buffBadge")]
            public Image buffBadge { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class PayGrade : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"totalDiamondCount")]
            public long totalDiamondCount { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"diamondIcon")]
            public Image diamondIcon { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"name")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Name { get; set; } = "";

            [global::ProtoBuf.ProtoMember(4, Name = @"icon")]
            public Image Icon { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"nextName")]
            [global::System.ComponentModel.DefaultValue("")]
            public string nextName { get; set; } = "";

            [global::ProtoBuf.ProtoMember(6, Name = @"level")]
            public long Level { get; set; }

            [global::ProtoBuf.ProtoMember(7, Name = @"nextIcon")]
            public Image nextIcon { get; set; }

            [global::ProtoBuf.ProtoMember(8, Name = @"nextDiamond")]
            public long nextDiamond { get; set; }

            [global::ProtoBuf.ProtoMember(9, Name = @"nowDiamond")]
            public long nowDiamond { get; set; }

            [global::ProtoBuf.ProtoMember(10, Name = @"thisGradeMinDiamond")]
            public long thisGradeMinDiamond { get; set; }

            [global::ProtoBuf.ProtoMember(11, Name = @"thisGradeMaxDiamond")]
            public long thisGradeMaxDiamond { get; set; }

            [global::ProtoBuf.ProtoMember(12, Name = @"payDiamondBak")]
            public long payDiamondBak { get; set; }

            [global::ProtoBuf.ProtoMember(13, Name = @"gradeDescribe")]
            [global::System.ComponentModel.DefaultValue("")]
            public string gradeDescribe { get; set; } = "";

            [global::ProtoBuf.ProtoMember(14, Name = @"gradeIconList")]
            public global::System.Collections.Generic.List<GradeIcon> gradeIconList { get; } = new global::System.Collections.Generic.List<GradeIcon>();

            [global::ProtoBuf.ProtoMember(15, Name = @"screenChatType")]
            public long screenChatType { get; set; }

            [global::ProtoBuf.ProtoMember(16, Name = @"imIcon")]
            public Image imIcon { get; set; }

            [global::ProtoBuf.ProtoMember(17, Name = @"imIconWithLevel")]
            public Image imIconWithLevel { get; set; }

            [global::ProtoBuf.ProtoMember(18, Name = @"liveIcon")]
            public Image liveIcon { get; set; }

            [global::ProtoBuf.ProtoMember(19, Name = @"newImIconWithLevel")]
            public Image newImIconWithLevel { get; set; }

            [global::ProtoBuf.ProtoMember(20, Name = @"newLiveIcon")]
            public Image newLiveIcon { get; set; }

            [global::ProtoBuf.ProtoMember(21, Name = @"upgradeNeedConsume")]
            public long upgradeNeedConsume { get; set; }

            [global::ProtoBuf.ProtoMember(22, Name = @"nextPrivileges")]
            [global::System.ComponentModel.DefaultValue("")]
            public string nextPrivileges { get; set; } = "";

            [global::ProtoBuf.ProtoMember(23, Name = @"background")]
            public Image Background { get; set; }

            [global::ProtoBuf.ProtoMember(24, Name = @"backgroundBack")]
            public Image backgroundBack { get; set; }

            [global::ProtoBuf.ProtoMember(25, Name = @"score")]
            public long Score { get; set; }

            [global::ProtoBuf.ProtoMember(26, Name = @"buffInfo")]
            public GradeBuffInfo buffInfo { get; set; }

            [global::ProtoBuf.ProtoMember(1001, Name = @"gradeBanner")]
            [global::System.ComponentModel.DefaultValue("")]
            public string gradeBanner { get; set; } = "";

            [global::ProtoBuf.ProtoMember(1002, Name = @"profileDialogBg")]
            public Image profileDialogBg { get; set; }

            [global::ProtoBuf.ProtoMember(1003, Name = @"profileDialogBgBack")]
            public Image profileDialogBgBack { get; set; }

            [global::ProtoBuf.ProtoContract()]
            public partial class GradeIcon : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"icon")]
                public Image Icon { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"iconDiamond")]
                public long iconDiamond { get; set; }

                [global::ProtoBuf.ProtoMember(3, Name = @"level")]
                public long Level { get; set; }

                [global::ProtoBuf.ProtoMember(4, Name = @"levelStr")]
                [global::System.ComponentModel.DefaultValue("")]
                public string levelStr { get; set; } = "";

            }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class FollowInfo : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"followingCount")]
            public long followingCount { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"followerCount")]
            public long followerCount { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"followStatus")]
            public long followStatus { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"pushStatus")]
            public long pushStatus { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"remarkName")]
            [global::System.ComponentModel.DefaultValue("")]
            public string remarkName { get; set; } = "";

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Subscribe : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"isMember")]
        public bool isMember { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"level")]
        public long Level { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"identityType")]
        public long identityType { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"buyType")]
        public long buyType { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"open")]
        public long Open { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FansClub : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"data")]
        public FansClubData Data { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, FansClubData> preferData { get; } = new global::System.Collections.Generic.Dictionary<int, FansClubData>();

        [global::ProtoBuf.ProtoContract()]
        public partial class FansClubData : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"clubName")]
            [global::System.ComponentModel.DefaultValue("")]
            public string clubName { get; set; } = "";

            [global::ProtoBuf.ProtoMember(2, Name = @"level")]
            public int Level { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"userFansClubStatus")]
            public int userFansClubStatus { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"badge")]
            public UserBadge Badge { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"availableGiftIds")]
            public global::System.Collections.Generic.List<long> availableGiftIds { get; } = new global::System.Collections.Generic.List<long>();

            [global::ProtoBuf.ProtoMember(6, Name = @"anchorId")]
            public long anchorId { get; set; }

            [global::ProtoBuf.ProtoContract()]
            public partial class UserBadge : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1)]
                [global::ProtoBuf.ProtoMap]
                public global::System.Collections.Generic.Dictionary<int, Image> Icons { get; } = new global::System.Collections.Generic.Dictionary<int, Image>();

                [global::ProtoBuf.ProtoMember(2, Name = @"title")]
                [global::System.ComponentModel.DefaultValue("")]
                public string Title { get; set; } = "";

            }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TextFormat : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"color")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Color { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"bold")]
        public bool Bold { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"italic")]
        public bool Italic { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"weight")]
        public int Weight { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"italicAngle")]
        public int italicAngle { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"fontSize")]
        public int fontSize { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"userHeightLightColor")]
        public bool userHeightLightColor { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"useRemoteClor")]
        public bool useRemoteClor { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TextPiece : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        public int Type { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"format")]
        public TextFormat Format { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"valueRef")]
        [global::System.ComponentModel.DefaultValue("")]
        public string valueRef { get; set; } = "";

        [global::ProtoBuf.ProtoMember(11, Name = @"stringValue")]
        [global::System.ComponentModel.DefaultValue("")]
        public string stringValue { get; set; } = "";

        [global::ProtoBuf.ProtoMember(21, Name = @"userValue")]
        public TextPieceUser userValue { get; set; }

        [global::ProtoBuf.ProtoMember(22, Name = @"giftValue")]
        public TextPieceGift giftValue { get; set; }

        [global::ProtoBuf.ProtoMember(25, Name = @"imageValue")]
        public TextPieceImage imageValue { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class TextPieceUser : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"user")]
            public User User { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class TextPieceGift : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"giftId")]
            public long giftId { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class TextPieceImage : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"image")]
            public Image Image { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Image : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"urlList")]
        public global::System.Collections.Generic.List<string> urlList { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(2, Name = @"uri")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Uri { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"height")]
        public long Height { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"width")]
        public long Width { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"avgColor")]
        [global::System.ComponentModel.DefaultValue("")]
        public string avgColor { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6, Name = @"imageType")]
        public int imageType { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"openWebUrl")]
        [global::System.ComponentModel.DefaultValue("")]
        public string openWebUrl { get; set; } = "";

        [global::ProtoBuf.ProtoMember(8, Name = @"content")]
        public Content Content { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"isAnimated")]
        public bool isAnimated { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Content : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"fontColor")]
        [global::System.ComponentModel.DefaultValue("")]
        public string fontColor { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"level")]
        public long Level { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"alternativeText")]
        [global::System.ComponentModel.DefaultValue("")]
        public string alternativeText { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PublicAreaCommon : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"userLabel")]
        public Image userLabel { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"userConsumeInRoom")]
        public long userConsumeInRoom { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"userSendGiftCntInRoom")]
        public long userSendGiftCntInRoom { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GiftIMPriority : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"queueSizes")]
        public global::System.Collections.Generic.List<long> queueSizes { get; } = new global::System.Collections.Generic.List<long>();

        [global::ProtoBuf.ProtoMember(2, Name = @"selfQueuePriority")]
        public long selfQueuePriority { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"priority")]
        public long Priority { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GiftTrayInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"trayDisplayText")]
        public Text trayDisplayText { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"trayBaseImg")]
        public Image trayBaseImg { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"trayHeadImg")]
        public Image trayHeadImg { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"trayRightImg")]
        public Image trayRightImg { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"trayLevel")]
        public long trayLevel { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"trayDynamicImg")]
        public Image trayDynamicImg { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GiftStruct : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"image")]
        public Image Image { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"describe")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Describe { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"notify")]
        public bool Notify { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"duration")]
        public long Duration { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"id")]
        public long Id { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"fansclubInfo")]
        public GiftStructFansClubInfo fansclubInfo { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"forLinkmic")]
        public bool forLinkmic { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"doodle")]
        public bool Doodle { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"forFansclub")]
        public bool forFansclub { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"combo")]
        public bool Combo { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"type")]
        public int Type { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"diamondCount")]
        public int diamondCount { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"isDisplayedOnPanel")]
        public int isDisplayedOnPanel { get; set; }

        [global::ProtoBuf.ProtoMember(14, Name = @"primaryEffectId")]
        public long primaryEffectId { get; set; }

        [global::ProtoBuf.ProtoMember(15, Name = @"giftLabelIcon")]
        public Image giftLabelIcon { get; set; }

        [global::ProtoBuf.ProtoMember(16, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(17, Name = @"region")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Region { get; set; } = "";

        [global::ProtoBuf.ProtoMember(18, Name = @"manual")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Manual { get; set; } = "";

        [global::ProtoBuf.ProtoMember(19, Name = @"forCustom")]
        public bool forCustom { get; set; }

        [global::ProtoBuf.ProtoMember(20)]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<string, long> specialEffects { get; } = new global::System.Collections.Generic.Dictionary<string, long>();

        [global::ProtoBuf.ProtoMember(21, Name = @"icon")]
        public Image Icon { get; set; }

        [global::ProtoBuf.ProtoMember(22, Name = @"actionType")]
        public int actionType { get; set; }

        [global::ProtoBuf.ProtoMember(23, Name = @"watermelonSeeds")]
        public int watermelonSeeds { get; set; }

        [global::ProtoBuf.ProtoMember(24, Name = @"goldEffect")]
        [global::System.ComponentModel.DefaultValue("")]
        public string goldEffect { get; set; } = "";

        [global::ProtoBuf.ProtoMember(25, Name = @"subs")]
        public global::System.Collections.Generic.List<LuckyMoneyGiftMeta> Subs { get; } = new global::System.Collections.Generic.List<LuckyMoneyGiftMeta>();

        [global::ProtoBuf.ProtoMember(26, Name = @"goldenBeans")]
        public long goldenBeans { get; set; }

        [global::ProtoBuf.ProtoMember(27, Name = @"honorLevel")]
        public long honorLevel { get; set; }

        [global::ProtoBuf.ProtoMember(28, Name = @"itemType")]
        public int itemType { get; set; }

        [global::ProtoBuf.ProtoMember(29, Name = @"schemeUrl")]
        [global::System.ComponentModel.DefaultValue("")]
        public string schemeUrl { get; set; } = "";

        [global::ProtoBuf.ProtoMember(30, Name = @"giftOperation")]
        public GiftPanelOperation giftOperation { get; set; }

        [global::ProtoBuf.ProtoMember(31, Name = @"eventName")]
        [global::System.ComponentModel.DefaultValue("")]
        public string eventName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(32, Name = @"nobleLevel")]
        public long nobleLevel { get; set; }

        [global::ProtoBuf.ProtoMember(33, Name = @"guideUrl")]
        [global::System.ComponentModel.DefaultValue("")]
        public string guideUrl { get; set; } = "";

        [global::ProtoBuf.ProtoMember(34, Name = @"punishMedicine")]
        public bool punishMedicine { get; set; }

        [global::ProtoBuf.ProtoMember(35, Name = @"forPortal")]
        public bool forPortal { get; set; }

        [global::ProtoBuf.ProtoMember(36, Name = @"businessText")]
        [global::System.ComponentModel.DefaultValue("")]
        public string businessText { get; set; } = "";

        [global::ProtoBuf.ProtoMember(37, Name = @"cnyGift")]
        public bool cnyGift { get; set; }

        [global::ProtoBuf.ProtoMember(38, Name = @"appId")]
        public long appId { get; set; }

        [global::ProtoBuf.ProtoMember(39, Name = @"vipLevel")]
        public long vipLevel { get; set; }

        [global::ProtoBuf.ProtoMember(40, Name = @"isGray")]
        public bool isGray { get; set; }

        [global::ProtoBuf.ProtoMember(41, Name = @"graySchemeUrl")]
        [global::System.ComponentModel.DefaultValue("")]
        public string graySchemeUrl { get; set; } = "";

        [global::ProtoBuf.ProtoMember(42, Name = @"giftScene")]
        public long giftScene { get; set; }

        [global::ProtoBuf.ProtoMember(43, Name = @"giftBanner")]
        public GiftBanner giftBanner { get; set; }

        [global::ProtoBuf.ProtoMember(44, Name = @"triggerWords")]
        public global::System.Collections.Generic.List<string> triggerWords { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(45, Name = @"giftBuffInfos")]
        public global::System.Collections.Generic.List<GiftBuffInfo> giftBuffInfos { get; } = new global::System.Collections.Generic.List<GiftBuffInfo>();

        [global::ProtoBuf.ProtoMember(46, Name = @"forFirstRecharge")]
        public bool forFirstRecharge { get; set; }

        [global::ProtoBuf.ProtoMember(47, Name = @"dynamicImgForSelected")]
        public Image dynamicImgForSelected { get; set; }

        [global::ProtoBuf.ProtoMember(48, Name = @"afterSendAction")]
        public int afterSendAction { get; set; }

        [global::ProtoBuf.ProtoMember(49, Name = @"giftOfflineTime")]
        public long giftOfflineTime { get; set; }

        [global::ProtoBuf.ProtoMember(50, Name = @"topBarText")]
        [global::System.ComponentModel.DefaultValue("")]
        public string topBarText { get; set; } = "";

        [global::ProtoBuf.ProtoMember(51, Name = @"topRightAvatar")]
        public Image topRightAvatar { get; set; }

        [global::ProtoBuf.ProtoMember(52, Name = @"bannerSchemeUrl")]
        [global::System.ComponentModel.DefaultValue("")]
        public string bannerSchemeUrl { get; set; } = "";

        [global::ProtoBuf.ProtoMember(53, Name = @"isLocked")]
        public bool isLocked { get; set; }

        [global::ProtoBuf.ProtoMember(54, Name = @"reqExtraType")]
        public long reqExtraType { get; set; }

        [global::ProtoBuf.ProtoMember(55, Name = @"assetIds")]
        public global::System.Collections.Generic.List<long> assetIds { get; } = new global::System.Collections.Generic.List<long>();

        [global::ProtoBuf.ProtoMember(56, Name = @"giftPreviewInfo")]
        public GiftPreviewInfo giftPreviewInfo { get; set; }

        [global::ProtoBuf.ProtoMember(57, Name = @"giftTip")]
        public GiftTip giftTip { get; set; }

        [global::ProtoBuf.ProtoMember(58, Name = @"needSweepLightCount")]
        public int needSweepLightCount { get; set; }

        [global::ProtoBuf.ProtoMember(59, Name = @"groupInfo")]
        public global::System.Collections.Generic.List<GiftGroupInfo> groupInfo { get; } = new global::System.Collections.Generic.List<GiftGroupInfo>();

        [global::ProtoBuf.ProtoContract()]
        public partial class GiftStructFansClubInfo : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"minLevel")]
            public int minLevel { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"insertPos")]
            public int insertPos { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AssetEffectMixInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LuckyMoneyGiftMeta : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GiftPanelOperation : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GiftBanner : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GiftBuffInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GiftPreviewInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GiftTip : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GiftGroupInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EffectMixImageInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UserVIPInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"vipLevel")]
        public long vipLevel { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"vipLevelName")]
        [global::System.ComponentModel.DefaultValue("")]
        public string vipLevelName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"status")]
        public int Status { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"startTime")]
        public long startTime { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"endTime")]
        public long endTime { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"remainingDays")]
        public long remainingDays { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"totalConsume")]
        public long totalConsume { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"targetConsume")]
        public long targetConsume { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"badge")]
        public VIPBadge Badge { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<long, bool> Privileges { get; } = new global::System.Collections.Generic.Dictionary<long, bool>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class VIPBadge : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<long, Image> Icons { get; } = new global::System.Collections.Generic.Dictionary<long, Image>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RoomUserSeqMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"common")]
        public Common Common { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"ranks")]
        public global::System.Collections.Generic.List<Contributor> Ranks { get; } = new global::System.Collections.Generic.List<Contributor>();

        [global::ProtoBuf.ProtoMember(3, Name = @"total")]
        public long Total { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"popStr")]
        [global::System.ComponentModel.DefaultValue("")]
        public string popStr { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"seats")]
        public global::System.Collections.Generic.List<Contributor> Seats { get; } = new global::System.Collections.Generic.List<Contributor>();

        [global::ProtoBuf.ProtoMember(6, Name = @"popularity")]
        public long Popularity { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"totalUser")]
        public long totalUser { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"totalUserStr")]
        [global::System.ComponentModel.DefaultValue("")]
        public string totalUserStr { get; set; } = "";

        [global::ProtoBuf.ProtoMember(9, Name = @"totalStr")]
        [global::System.ComponentModel.DefaultValue("")]
        public string totalStr { get; set; } = "";

        [global::ProtoBuf.ProtoMember(10, Name = @"onlineUserForAnchor")]
        [global::System.ComponentModel.DefaultValue("")]
        public string onlineUserForAnchor { get; set; } = "";

        [global::ProtoBuf.ProtoMember(11, Name = @"totalPvForAnchor")]
        [global::System.ComponentModel.DefaultValue("")]
        public string totalPvForAnchor { get; set; } = "";

        [global::ProtoBuf.ProtoContract()]
        public partial class Contributor : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"score")]
            public long Score { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"user")]
            public User User { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"rank")]
            public long Rank { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"delta")]
            public long Delta { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"isHidden")]
            public bool isHidden { get; set; }

            [global::ProtoBuf.ProtoMember(6, Name = @"scoreDescription")]
            [global::System.ComponentModel.DefaultValue("")]
            public string scoreDescription { get; set; } = "";

            [global::ProtoBuf.ProtoMember(7, Name = @"exactlyScore")]
            [global::System.ComponentModel.DefaultValue("")]
            public string exactlyScore { get; set; } = "";

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GiftMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"common")]
        public Common Common { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"giftId")]
        public long giftId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"fanTicketCount")]
        public long fanTicketCount { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"groupCount")]
        public long groupCount { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"repeatCount")]
        public long repeatCount { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"comboCount")]
        public long comboCount { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"user")]
        public User User { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"toUser")]
        public User toUser { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"repeatEnd")]
        public int repeatEnd { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"textEffect")]
        public TextEffect textEffect { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"groupId")]
        public long groupId { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"incomeTaskgifts")]
        public long incomeTaskgifts { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"roomFanTicketCount")]
        public long roomFanTicketCount { get; set; }

        [global::ProtoBuf.ProtoMember(14, Name = @"priority")]
        public GiftIMPriority Priority { get; set; }

        [global::ProtoBuf.ProtoMember(15, Name = @"gift")]
        public GiftStruct Gift { get; set; }

        [global::ProtoBuf.ProtoMember(16, Name = @"logId")]
        [global::System.ComponentModel.DefaultValue("")]
        public string logId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(17, Name = @"sendType")]
        public long sendType { get; set; }

        [global::ProtoBuf.ProtoMember(18, Name = @"publicAreaCommon")]
        public PublicAreaCommon publicAreaCommon { get; set; }

        [global::ProtoBuf.ProtoMember(19, Name = @"trayDisplayText")]
        public Text trayDisplayText { get; set; }

        [global::ProtoBuf.ProtoMember(20, Name = @"bannedDisplayEffects")]
        public long bannedDisplayEffects { get; set; }

        [global::ProtoBuf.ProtoMember(21, Name = @"trayInfo")]
        public GiftTrayInfo trayInfo { get; set; }

        [global::ProtoBuf.ProtoMember(24, Name = @"assetEffectMixInfo")]
        public AssetEffectMixInfo assetEffectMixInfo { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class TextEffect : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"portrait")]
            public Detail Portrait { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"landscape")]
            public Detail Landscape { get; set; }

            [global::ProtoBuf.ProtoContract()]
            public partial class Detail : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"text")]
                public Text Text { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"textFontSize")]
                public int textFontSize { get; set; }

                [global::ProtoBuf.ProtoMember(3, Name = @"background")]
                public Image Background { get; set; }

                [global::ProtoBuf.ProtoMember(4, Name = @"start")]
                public int Start { get; set; }

                [global::ProtoBuf.ProtoMember(5, Name = @"duration")]
                public int Duration { get; set; }

                [global::ProtoBuf.ProtoMember(6, Name = @"x")]
                public int X { get; set; }

                [global::ProtoBuf.ProtoMember(7, Name = @"y")]
                public int Y { get; set; }

                [global::ProtoBuf.ProtoMember(8, Name = @"width")]
                public int Width { get; set; }

                [global::ProtoBuf.ProtoMember(9, Name = @"height")]
                public int Height { get; set; }

                [global::ProtoBuf.ProtoMember(10, Name = @"shadowDx")]
                public int shadowDx { get; set; }

                [global::ProtoBuf.ProtoMember(11, Name = @"shadowDy")]
                public int shadowDy { get; set; }

                [global::ProtoBuf.ProtoMember(12, Name = @"shadowRadius")]
                public int shadowRadius { get; set; }

                [global::ProtoBuf.ProtoMember(13, Name = @"shadowColor")]
                [global::System.ComponentModel.DefaultValue("")]
                public string shadowColor { get; set; } = "";

                [global::ProtoBuf.ProtoMember(14, Name = @"strokeColor")]
                [global::System.ComponentModel.DefaultValue("")]
                public string strokeColor { get; set; } = "";

                [global::ProtoBuf.ProtoMember(15, Name = @"strokeWidth")]
                public int strokeWidth { get; set; }

            }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LikeMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"common")]
        public Common Common { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"count")]
        public long Count { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"total")]
        public long Total { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"color")]
        public long Color { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"user")]
        public User User { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"icon")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Icon { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChatMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"common")]
        public Common Common { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"user")]
        public User User { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"content")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Content { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"visibleToSender")]
        public bool visibleToSender { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"backgroundImage")]
        public Image backgroundImage { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"fullScreenTextColor")]
        [global::System.ComponentModel.DefaultValue("")]
        public string fullScreenTextColor { get; set; } = "";

        [global::ProtoBuf.ProtoMember(7, Name = @"backgroundImageV2")]
        public Image backgroundImageV2 { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"publicAreaCommon")]
        public PublicAreaCommon publicAreaCommon { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"giftImage")]
        public Image giftImage { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SocialMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"common")]
        public Common Common { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"user")]
        public User User { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"shareType")]
        public long shareType { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"action")]
        public long Action { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"shareTarget")]
        [global::System.ComponentModel.DefaultValue("")]
        public string shareTarget { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6, Name = @"followCount")]
        public long followCount { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"publicAreaCommon")]
        public PublicAreaCommon publicAreaCommon { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MemberMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"common")]
        public Common Common { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"user")]
        public User User { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"memberCount")]
        public long memberCount { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"operator")]
        public User Operator { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"isSetToAdmin")]
        public bool isSetToAdmin { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"isTopUser")]
        public bool isTopUser { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"rankScore")]
        public long rankScore { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"topUserNo")]
        public long topUserNo { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"enterType")]
        public long enterType { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"action")]
        public long Action { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"actionDescription")]
        [global::System.ComponentModel.DefaultValue("")]
        public string actionDescription { get; set; } = "";

        [global::ProtoBuf.ProtoMember(12, Name = @"userId")]
        public long userId { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"effectConfig")]
        public EffectConfig effectConfig { get; set; }

        [global::ProtoBuf.ProtoMember(14, Name = @"popStr")]
        [global::System.ComponentModel.DefaultValue("")]
        public string popStr { get; set; } = "";

        [global::ProtoBuf.ProtoMember(15, Name = @"enterEffectConfig")]
        public EffectConfig enterEffectConfig { get; set; }

        [global::ProtoBuf.ProtoMember(16, Name = @"backgroundImage")]
        public Image backgroundImage { get; set; }

        [global::ProtoBuf.ProtoMember(17, Name = @"backgroundImageV2")]
        public Image backgroundImageV2 { get; set; }

        [global::ProtoBuf.ProtoMember(18, Name = @"anchorDisplayText")]
        public Text anchorDisplayText { get; set; }

        [global::ProtoBuf.ProtoMember(19, Name = @"publicAreaCommon")]
        public PublicAreaCommon publicAreaCommon { get; set; }

        [global::ProtoBuf.ProtoMember(20, Name = @"userEnterTipType")]
        public long userEnterTipType { get; set; }

        [global::ProtoBuf.ProtoMember(21, Name = @"anchorEnterTipType")]
        public long anchorEnterTipType { get; set; }

        [global::ProtoBuf.ProtoMember(22)]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<string, string> buriedPoint { get; } = new global::System.Collections.Generic.Dictionary<string, string>();

        [global::ProtoBuf.ProtoMember(23)]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<string, EffectConfig> alternativeEffectConfig { get; } = new global::System.Collections.Generic.Dictionary<string, EffectConfig>();

        [global::ProtoBuf.ProtoMember(24, Name = @"picoEnterEffectConfig")]
        public PicoEffectConfig picoEnterEffectConfig { get; set; }

        [global::ProtoBuf.ProtoMember(25, Name = @"unsetAdminType")]
        public int unsetAdminType { get; set; }

        [global::ProtoBuf.ProtoMember(5000, Name = @"userOpenId")]
        [global::System.ComponentModel.DefaultValue("")]
        public string userOpenId { get; set; } = "";

        [global::ProtoBuf.ProtoContract()]
        public partial class EffectConfig : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"type")]
            public long Type { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"icon")]
            public Image Icon { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"avatarPos")]
            public long avatarPos { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"text")]
            public Text Text { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"textIcon")]
            public Image textIcon { get; set; }

            [global::ProtoBuf.ProtoMember(6, Name = @"stayTime")]
            public int stayTime { get; set; }

            [global::ProtoBuf.ProtoMember(7, Name = @"animAssetId")]
            public long animAssetId { get; set; }

            [global::ProtoBuf.ProtoMember(8, Name = @"badge")]
            public Image Badge { get; set; }

            [global::ProtoBuf.ProtoMember(9, Name = @"flexSettingArray")]
            public global::System.Collections.Generic.List<long> flexSettingArray { get; } = new global::System.Collections.Generic.List<long>();

            [global::ProtoBuf.ProtoMember(10, Name = @"textIconOverlay")]
            public Image textIconOverlay { get; set; }

            [global::ProtoBuf.ProtoMember(11, Name = @"animatedBadge")]
            public Image animatedBadge { get; set; }

            [global::ProtoBuf.ProtoMember(12, Name = @"hasSweepLight")]
            public bool hasSweepLight { get; set; }

            [global::ProtoBuf.ProtoMember(13, Name = @"textFlexSettingArray")]
            public global::System.Collections.Generic.List<long> textFlexSettingArray { get; } = new global::System.Collections.Generic.List<long>();

            [global::ProtoBuf.ProtoMember(14, Name = @"centerAnimAssetId")]
            public long centerAnimAssetId { get; set; }

            [global::ProtoBuf.ProtoMember(15, Name = @"dynamicImage")]
            public Image dynamicImage { get; set; }

            [global::ProtoBuf.ProtoMember(16)]
            [global::ProtoBuf.ProtoMap]
            public global::System.Collections.Generic.Dictionary<string, string> Extra { get; } = new global::System.Collections.Generic.Dictionary<string, string>();

            [global::ProtoBuf.ProtoMember(17, Name = @"mp4AnimAssetId")]
            public long mp4AnimAssetId { get; set; }

            [global::ProtoBuf.ProtoMember(18, Name = @"priority")]
            public long Priority { get; set; }

            [global::ProtoBuf.ProtoMember(19, Name = @"maxWaitTime")]
            public long maxWaitTime { get; set; }

            [global::ProtoBuf.ProtoMember(20, Name = @"dressId")]
            [global::System.ComponentModel.DefaultValue("")]
            public string dressId { get; set; } = "";

            [global::ProtoBuf.ProtoMember(21, Name = @"alignment")]
            public long Alignment { get; set; }

            [global::ProtoBuf.ProtoMember(22, Name = @"alignmentOffset")]
            public long alignmentOffset { get; set; }

            [global::ProtoBuf.ProtoMember(23, Name = @"effectScene")]
            [global::System.ComponentModel.DefaultValue("")]
            public string effectScene { get; set; } = "";

            [global::ProtoBuf.ProtoMember(24)]
            [global::ProtoBuf.ProtoMap]
            public global::System.Collections.Generic.Dictionary<string, TextPiece> pieceValues { get; } = new global::System.Collections.Generic.Dictionary<string, TextPiece>();

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class PicoEffectConfig : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"type")]
            public long Type { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"icon")]
            public Image Icon { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"text")]
            public Text Text { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"textIcon")]
            public Image textIcon { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"stayTime")]
            public int stayTime { get; set; }

            [global::ProtoBuf.ProtoMember(6, Name = @"badge")]
            public Image Badge { get; set; }

            [global::ProtoBuf.ProtoMember(7, Name = @"centerAnimAssetId")]
            public long centerAnimAssetId { get; set; }

            [global::ProtoBuf.ProtoMember(8)]
            [global::ProtoBuf.ProtoMap]
            public global::System.Collections.Generic.Dictionary<string, string> Extra { get; } = new global::System.Collections.Generic.Dictionary<string, string>();

            [global::ProtoBuf.ProtoMember(9, Name = @"dressId")]
            [global::System.ComponentModel.DefaultValue("")]
            public string dressId { get; set; } = "";

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ControlMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"common")]
        public Common Common { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"status")]
        public int Status { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EmojiChatMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"common")]
        public Common Common { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"user")]
        public User User { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"emojiId")]
        public long emojiId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"emojiContent")]
        public Text emojiContent { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"defaultContent")]
        [global::System.ComponentModel.DefaultValue("")]
        public string defaultContent { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6, Name = @"backgroundImage")]
        public Image backgroundImage { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"fromIntercom")]
        public bool fromIntercom { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LotteryEventMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"common")]
        public Common Common { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"lotteryId")]
        public long lotteryId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"lotteryStatus")]
        public int lotteryStatus { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"lotteryStartTime")]
        public long lotteryStartTime { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"lotteryDrawTime")]
        public long lotteryDrawTime { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"lotteryCurrentTime")]
        public long lotteryCurrentTime { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"rulePageScheme")]
        [global::System.ComponentModel.DefaultValue("")]
        public string rulePageScheme { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AudioChatMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"common")]
        public Common Common { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"user")]
        public User User { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"content")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Content { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"audioUrl")]
        [global::System.ComponentModel.DefaultValue("")]
        public string audioUrl { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"audioDuration")]
        public long audioDuration { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"publicAreaCommon")]
        public PublicAreaCommon publicAreaCommon { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"rtfContent")]
        public Text rtfContent { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FansclubMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"common")]
        public Common Common { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"action")]
        public int Action { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"content")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Content { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"user")]
        public User User { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"upgrade_privilege")]
        public UpgradePrivilege Upgrade_privilege { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"left_diamond")]
        public long Left_diamond { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class UpgradePrivilege : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"content")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Content { get; set; } = "";

            [global::ProtoBuf.ProtoMember(2, Name = @"description")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Description { get; set; } = "";

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RoomMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"common")]
        public Common Common { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"content")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Content { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"roomMessageType")]
        public int roomMessageType { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"system_top_msg")]
        public bool System_top_msg { get; set; }

        [global::ProtoBuf.ProtoMember(20, Name = @"biz_scene")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Biz_scene { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RoomStatsMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"common")]
        public Common Common { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"display")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Display { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"displaValue")]
        public long displaValue { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"incremental")]
        public bool Incremental { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"total")]
        public long Total { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RoomRankMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"common")]
        public Common Common { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"ranks")]
        public global::System.Collections.Generic.List<RoomRank> Ranks { get; } = new global::System.Collections.Generic.List<RoomRank>();

        [global::ProtoBuf.ProtoContract()]
        public partial class RoomRank : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"user")]
            public User User { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"score")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Score { get; set; } = "";

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ExhibitionChatMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"common")]
        public Common Common { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"displayText")]
        public Text displayText { get; set; }

    }


}
