const protobuf = require('protobufjs');
const fs = require('fs');
const os = require('os');
const path = require('path');

function readArg(name, fallback) {
    const index = process.argv.indexOf(name);
    return index >= 0 && process.argv[index + 1]
        ? path.resolve(process.cwd(), process.argv[index + 1])
        : fallback;
}

const PROTO_PATH = readArg('--input', path.resolve(__dirname, '../proto/message.proto'));
const OUT_PATH = readArg(
    '--output',
    path.join(os.tmpdir(), 'DanmakuBackend.GenProto', 'Messages.cs')
);
const NAMESPACE = process.env.GENPROTO_NAMESPACE || 'DanmakuBackend.Models.ProtoEntity';

// Type mapping for C#
const typeMap = {
    'double': 'double',
    'float': 'float',
    'int32': 'int',
    'int64': 'long',
    'uint32': 'uint',
    'uint64': 'ulong',
    'sint32': 'int',
    'sint64': 'long',
    'fixed32': 'uint',
    'fixed64': 'ulong',
    'sfixed32': 'int',
    'sfixed64': 'long',
    'bool': 'bool',
    'string': 'string',
    'bytes': 'byte[]'
};

function toPascal(name) {
    if (!name) return name;
    // Heuristic: If all lowercase, PascalCase it. Otherwise preserve.
    // Exception: msgId -> msgId (starts with lower, has upper).
    // check if all lowercase
    if (name === name.toLowerCase()) {
        return name.charAt(0).toUpperCase() + name.slice(1);
    }
    return name;
}

function generateHeader() {
    return `// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: message.proto
// </auto-generated>

using System.Collections.Generic;
using Newtonsoft.Json;

namespace ${NAMESPACE}
{
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
`;
}

function generateFooter() {
    return `
}
`;
}

function generateClass(type, indentLevel) {
    const indent = '    '.repeat(indentLevel);
    const memberIndent = '    '.repeat(indentLevel + 1);
    let sb = '';

    sb += `${indent}[global::ProtoBuf.ProtoContract()]\n`;
    sb += `${indent}public partial class ${type.name} : global::ProtoBuf.IExtensible\n`;
    sb += `${indent}{\n`;
    sb += `${memberIndent}private global::ProtoBuf.IExtension __pbn__extensionData;\n`;
    sb += `${memberIndent}global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)\n`;
    sb += `${memberIndent}    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);\n\n`;

    // Fields
    if (type.fieldsArray) {
        type.fieldsArray.forEach(field => {
            const csName = toPascal(field.name);
            const isMap = field.map;
            const isRepeated = field.repeated;
            let csType = typeMap[field.type] || field.type;

            // Resolve relative types if needed? protobufjs usually resolves them or gives strings.
            // If it is a message type, we preserve the name.

            // Special handling for namespaces if needed. Assuming all in same namespace.

            if (isMap) {
                const keyType = typeMap[field.keyType] || field.keyType;
                sb += `${memberIndent}[global::ProtoBuf.ProtoMember(${field.id})]\n`;
                sb += `${memberIndent}[global::ProtoBuf.ProtoMap]\n`;
                sb += `${memberIndent}public global::System.Collections.Generic.Dictionary<${keyType}, ${csType}> ${csName} { get; } = new global::System.Collections.Generic.Dictionary<${keyType}, ${csType}>();\n`;
            } else if (isRepeated) {
                sb += `${memberIndent}[global::ProtoBuf.ProtoMember(${field.id}, Name = @"${field.name}")]\n`;
                sb += `${memberIndent}public global::System.Collections.Generic.List<${csType}> ${csName} { get; } = new global::System.Collections.Generic.List<${csType}>();\n`;
            } else {
                sb += `${memberIndent}[global::ProtoBuf.ProtoMember(${field.id}, Name = @"${field.name}")]\n`;

                if (csType === 'string') {
                    sb += `${memberIndent}[global::System.ComponentModel.DefaultValue("")]\n`;
                    sb += `${memberIndent}public ${csType} ${csName} { get; set; } = "";\n`;
                } else {
                    sb += `${memberIndent}public ${csType} ${csName} { get; set; }\n`;
                }
            }
            sb += '\n';
        });
    }

    // Nested types
    if (type.nestedArray) {
        type.nestedArray.forEach(nested => {
            if (nested instanceof protobuf.Type) {
                sb += generateClass(nested, indentLevel + 1);
            }
        });
    }

    sb += `${indent}}\n\n`;
    return sb;
}

function main() {
    const root = new protobuf.Root();
    try {
        root.loadSync(PROTO_PATH, { keepCase: true }); // keepCase: true is important to get original names
    } catch (e) {
        console.error("Failed to load proto:", e);
        process.exit(1);
    }

    let code = generateHeader();

    // Iterate over top-level messages
    if (root.nestedArray) {
        root.nestedArray.forEach(nested => {
            if (nested instanceof protobuf.Type) {
                code += generateClass(nested, 1);
            }
        });
    }

    code += generateFooter();

    fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
    fs.writeFileSync(OUT_PATH, code, 'utf8');
    console.log(`Successfully generated C# code at ${OUT_PATH}`);
}

main();
